# Generated by Django 4.1.2 on 2022-10-24 15:33

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='pet_photos', validators=[petstagram.photos.validators.validate_image]),
        ),
    ]
