# Generated by Django 4.1.2 on 2022-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personal_pet_photo',
            field=models.URLField(blank=True),
        ),
    ]
