# Generated by Django 4.1.2 on 2022-10-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='personal_pet_photo',
            field=models.URLField(),
        ),
    ]
